### ISSUE TITLE
Custom Tutorial Gamemode Series

### ISSUE THREAD

**Issue by plexx-0w0** [FoksVHox/Dan-Video-Suggestions#52] opened 2020-06-21 17:08 UTC
**Suggestion:**

 Maybe a Custom Tutorial Gamemode Series where you create a not complicated Gamemode but you tell us how to get started making one.

**Gamemode:**

the tutorial

**Relevant resources:**

*None*

**Comment by FoksVHox** [comment] 2020-06-21 17:35
Dupe of #26

**Closed by FoksVHox** 2020-06-21 17:35 UTC
Labels: duplicate
